import = [
    "~/.config/alacritty/gruvbox_material_medium_dark.custom.toml"
]

[env]
TERM = "xterm-256color"

[shell]

program = "/bin/zsh"

[window]

opacity = 0.85
blur = true
decorations = "None"
padding = {x = 10, y = 10}

[font]
# normal = { family = "Departure Mono", style = "Regular" }
normal = { family = "Iosevka Nerd Font", style = "SemiBold Extended" }
bold = { family = "Iosevka Nerd Font", style = "SemiBold Extended" }
italic = { family = "Iosevka Nerd Font", style = "SemiBold Extended" }
bold_italic = { family = "Iosevka Nerd Font", style = "SemiBold Extended" }

size = 24

[selection]

save_to_clipboard = true

[keyboard]
bindings = [
    {key = "H", mods = "Control|Shift", chars = "\u001b[72;6u"},
    {key = "L", mods = "Control|Shift", chars = "\u001b[76;6u"},

    {key = "<", mods = "Control|Shift", chars = "\u001b[60;6u"},
    {key = ">", mods = "Control|Shift", chars = "\u001b[62;6u"},

    {key = "Enter", mods = "Control|Shift", chars = "\u001b[13;6u"},
    {key = "}", mods = "Control|Shift", chars = "\u001b[125;6u"},

    {key = "T", mods = "Control|Shift", chars = "\u001b[84;6u"},
    {key = "N", mods = "Control|Shift", chars = "\u001b[78;6u"},

    {key = "W", mods = "Control|Shift", chars = "\u001b[87;6u"},
    {key = "I", mods = "Control|Shift", chars = "\u001b[73;6u"},

    {key = "{", mods = "Control|Shift", chars = "\u001b[123;6u"},
]
